belugaAI:
  alpha: 0.0
  batch_size: 32
  beta: 1.0
  beta_increment: 0.0001
  checkpoint: ''
  discount_factor: 0.99
  enable_double_DQN: true
  enable_dueling_DQN: true
  env_id: BelugaAI
  epsilon_decay: 0.995
  epsilon_end: 0.05
  epsilon_start: 1.0
  hidden_dims: 256
  lr: 0.0001
  lr_decay_step: 300
  maximum_simulation_steps: 1000
  network_sync_rate: 100
  prior_data: ''
  replay_memory_size: 100000
